"""Added fx_rates and fx_tracking_pairs

Revision ID: f8c2eb76c2a0
Revises: 
Create Date: 2025-04-13 18:08:56.731339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8c2eb76c2a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('currency_code_from', sa.String(length=3), nullable=False),
    sa.Column('currency_code_to', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=38, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('date', 'currency_code_from', 'currency_code_to', name='fx_rates_unique_idx')
    )
    op.create_table('fx_tracking_pairs',
    sa.Column('currency_code_from', sa.String(length=3), nullable=False),
    sa.Column('currency_code_to', sa.String(length=3), nullable=False),
    sa.Column('sources_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_sync_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_sync_status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('currency_code_from', 'currency_code_to', name='fx_tracking_pairs_unique_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fx_tracking_pairs')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
